version: "3.7"
services:
  speedlogger-web:
    image: brennentsmith/internet-speed-logger
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./config:/data/config
  speedlogger-runner:
    image: brennentsmith/internet-speed-logger
    depends_on:
      - speedlogger-web
    restart: always
    entrypoint:
      - node
      - run-speedtest.js
      - daemon
    volumes:
      - ./config:/data/config
  mongo:
    image: mongo
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=speedtest
      - MONGO_INITDB_ROOT_PASSWORD=speedtest
      - MONGO_INITDB_DATABASE=speedtest
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./mongo-persistence:/data/db
